# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_auto_20150515_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='activity_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='approval_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bmsg_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='credit_rating',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cust_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='drivers_license',
        ),
        migrations.RemoveField(
            model_name='account',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='account',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ethn_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name_sdx',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lang_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name_sdx',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name_upr',
        ),
        migrations.RemoveField(
            model_name='account',
            name='letr_ind',
        ),
        migrations.RemoveField(
            model_name='account',
            name='lrg_prnt_ind',
        ),
        migrations.RemoveField(
            model_name='account',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='middle_name_sdx',
        ),
        migrations.RemoveField(
            model_name='account',
            name='mmbr_type_ind',
        ),
        migrations.RemoveField(
            model_name='account',
            name='natn_code_d_l',
        ),
        migrations.RemoveField(
            model_name='account',
            name='pay_by_check_ind',
        ),
        migrations.RemoveField(
            model_name='account',
            name='pidm',
        ),
        migrations.RemoveField(
            model_name='account',
            name='spouses_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='spouses_ssn',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ssn',
        ),
        migrations.RemoveField(
            model_name='account',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='stat_code_d_l',
        ),
        migrations.RemoveField(
            model_name='account',
            name='status_ind',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ten99_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ten99_ind',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ten99_primary_ind',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ten99_state',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ten99_wh_pct',
        ),
        migrations.RemoveField(
            model_name='account',
            name='title',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_id',
        ),
        migrations.AddField(
            model_name='account',
            name='account',
            field=models.CharField(max_length=100, null=True, verbose_name=b'Account number'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='account',
            name='addr',
            field=models.CharField(max_length=250, null=True, verbose_name=b'Address'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='account',
            name='cycle',
            field=models.CharField(max_length=100, null=True, verbose_name=b'Cycle'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name=b'Name'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='account',
            name='rate',
            field=models.CharField(max_length=100, null=True, verbose_name=b'Rate'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='account',
            name='tou',
            field=models.CharField(max_length=100, null=True, verbose_name=b'TOU'),
            preserve_default=True,
        ),
    ]
